# Vibe Coding: Real-World Data Cleaning Challenge

## The Mission

You're a Data Analyst at **TechSalary Insights**. Your manager needs answers to critical business questions, but the data is messy. Your job is to clean it and provide accurate insights.

**The catch:** You must figure out how to clean the data yourself. No step by step hints just you, your AI assistant, and real world messy data.

---

## The Dataset: Ask A Manager Salary Survey 2021

**Location:** `../Week-02-Pandas-Part-2-and-DS-Overview/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`

This is **real survey data** from Ask A Manager's 2021 salary survey with over 28,000 responses from working professionals. The data comes from this survey: https://www.askamanager.org/2021/04/how-much-money-do-you-make-4.html

**Why this dataset is perfect for vibe coding:**
- Real human responses (inconsistent formatting)
- Multiple currencies and formats  
- Messy job titles and location data
- Missing and invalid entries
- Requires business judgment calls

---

## Your Business Questions

Answer these **exact questions** with clean data. There's only one correct answer for each:

### Core Questions (Required):
1. **What is the median salary for Software Engineers in the United States?** 
2. **Which US state has the highest average salary for tech workers?**
3. **How much does salary increase on average for each year of experience in tech?**
4. **Which industry (besides tech) has the highest median salary?**

### Bonus Questions (If time permits):
5. **What's the salary gap between men and women in tech roles?**
6. **Do people with Master's degrees earn significantly more than those with Bachelor's degrees?**

**Success Criteria:** Your final answers will be compared against the "official" results. Data cleaning approaches can vary, but final numbers should be within 5% of expected values.


---
# Your Work Starts Here

## Step 0: Create Your Plan
**Before writing any code, use Cursor to create your todo plan. Then paste it here:**

## My Data Cleaning Plan

### 📦 Setup
- [ ] Import pandas, numpy, matplotlib, seaborn
- [ ] Load TSV data from path: `../Week-02-Pandas-Part-2-and-DS-Overview/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv`
- [ ] Inspect shape, columns, and data types
- [ ] Check for duplicates or missing values

### 🧹 Cleaning Salary Data
- [ ] Clean salary column:
  - Remove text and symbols ($, commas, etc.)
  - Handle multiple currencies (convert to USD where possible)
  - Filter out extreme outliers (e.g. < $10k or > $1M)
- [ ] Convert salary to numeric

### 🧠 Cleaning Job Titles
- [ ] Normalize job titles (lowercase, strip spaces)
- [ ] Use keyword matching to identify “Software Engineer” and other tech roles
- [ ] Create a binary column: `is_tech = True/False`

### 🗺️ Cleaning Location Data
- [ ] Standardize country names
- [ ] Filter only respondents in the U.S.
- [ ] Extract state (normalize abbreviations like “CA”, “California”)
- [ ] Handle “remote” responses

### 📈 Experience & Education
- [ ] Convert “Years of experience” and “Years at current company” to numeric
- [ ] Clean education column → extract “Bachelor’s”, “Master’s”, “PhD”, etc.

### 🧾 Analysis Goals
- [ ] Median U.S. Software Engineer salary
- [ ] State with highest average tech salary
- [ ] Average salary increase per year of experience
- [ ] Highest median non-tech industry salary
- [ ] (Bonus) Gender pay gap in tech
- [ ] (Bonus) Master’s vs. Bachelor’s pay comparison

### 📊 Output
- [ ] Summarize final answers in markdown table
- [ ] Create 2–3 visualizations (e.g., salary by state, salary vs. experience)
- [ ] Document findings clearly



## Step 1: Data Loading and Exploration

Start here! Load the dataset and get familiar with what you're working with.


In [1]:
# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path = "/workspaces/ds-fall-2025-fri-0630/Week-02-Pandas-Part-2-and-DS-Overview/data/Ask A Manager Salary Survey 2021 (Responses) - Form Responses 1.tsv"
df = pd.read_csv(path, sep='\t')

print(df.shape)
df.head()

(28062, 18)


Timestamp How old are you?  What industry do you work in?  \
0  4/27/2021 11:02:10            25-34   Education (Higher Education)   
1  4/27/2021 11:02:22            25-34              Computing or Tech   
2  4/27/2021 11:02:38            25-34  Accounting, Banking & Finance   
3  4/27/2021 11:02:41            25-34                     Nonprofits   
4  4/27/2021 11:02:42            25-34  Accounting, Banking & Finance   

                                  Job title  \
0        Research and Instruction Librarian   
1  Change & Internal Communications Manager   
2                      Marketing Specialist   
3                           Program Manager   
4                        Accounting Manager   

  If your job title needs additional context, please clarify here:  \
0                                                NaN                 
1                                                NaN                 
2                                                NaN                 
3                                                NaN                 
4                                                NaN                 

  What is your annual salary? (You'll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)  \
0                                             55,000                                                                                                                                                                                     
1                                             54,600                                                                                                                                                                                     
2                                             34,000                                                                                                                                                                                     
3                                             62,000                                                                                                                                                                                     
4                                             60,000                                                                                                                                                                                     

   How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.  \
0                                                0.0                                                                                                                                                
1                                             4000.0                                                                                                                                                
2                                                NaN                                                                                                                                                
3                                             3000.0                                                                                                                                                
4                                             7000.0                                                                                                                                                

  Please indicate the currency  \
0                          USD   
1                          GBP   
2                          USD   
3                          USD   
4                          USD   

  If "Other," please indicate the currency here:   \
0                      

## Step 2: Data Cleaning


In [ ]:
#Rename key columns for readability
df = df.rename(columns={
    'What is your annual salary? (You\'ll indicate the currency in a later question. If you are part-time or hourly, please enter an annualized equivalent -- what you would earn if you worked the job 40 hours a week, 52 weeks a year.)': 'annual_salary',
    'How much additional monetary compensation do you get, if any (for example, bonuses or overtime in an average year)? Please only include monetary compensation here, not the value of benefits.': 'additional_comp',
    'Please indicate the currency': 'currency',
    'What country do you work in?': 'country',
    'If you\'re in the U.S., what state do you work in?': 'state',
    'What industry do you work in?': 'industry',
    'Job title': 'job_title',
    'How many years of professional work experience do you have overall?': 'experience_overall'
})

#Clean numeric fields (salary and bonus)
def clean_money(x):
    if pd.isna(x): 
        return np.nan
    if isinstance(x, str):
        x = x.replace(',', '').replace('$', '').replace('€', '').strip()
    try:
        return float(x)
    except:
        return np.nan

df['annual_salary'] = df['annual_salary'].apply(clean_money)
df['additional_comp'] = df['additional_comp'].apply(clean_money)

#Fill missing 'additional_comp' with 0 for simplicity
df['additional_comp'] = df['additional_comp'].fillna(0)

#Total comp = base salary + additional comp
df['total_comp'] = df['annual_salary'] + df['additional_comp']

#Normalize country strings
df['country'] = df['country'].str.strip().str.lower()
df['country'] = df['country'].replace({
    'us': 'united states',
    'usa': 'united states',
    'u.s.': 'united states',
    'u.s.a.': 'united states'
})

#Filter for valid numeric salaries
df = df[(df['total_comp'] > 10000) & (df['total_comp'] < 1_000_000)]

print("Rows after cleaning:", len(df))
df[['job_title', 'industry', 'country', 'state', 'currency', 'total_comp']].head(10)

Rows after cleaning: 27823


job_title                       industry  \
0        Research and Instruction Librarian   Education (Higher Education)   
1  Change & Internal Communications Manager              Computing or Tech   
2                      Marketing Specialist  Accounting, Banking & Finance   
3                           Program Manager                     Nonprofits   
4                        Accounting Manager  Accounting, Banking & Finance   
5            Scholarly Publishing Librarian   Education (Higher Education)   
6                      Publishing Assistant                     Publishing   
7                                 Librarian  Education (Primary/Secondary)   
8                           Systems Analyst              Computing or Tech   
9                         Senior Accountant  Accounting, Banking & Finance   

          country           state currency  total_comp  
0   united states   Massachusetts      USD     55000.0  
1  united kingdom             NaN      GBP     58600.0  
2   united states       Tennessee      USD     34000.0  
3   united states       Wisconsin      USD     65000.0  
4   united states  South Carolina      USD     67000.0  
5   united states   New Hampshire      USD     62000.0  
6   united states  South Carolina      USD     35000.0  
7   united states         Arizona      USD     50000.0  
8   united states        Missouri      USD    122000.0  
9   united states         Florida      USD     45000.0

In [ ]:
us_df = df[df['country'] == 'united states'].copy()

# Normalize job titles
us_df['job_title_clean'] = (
    us_df['job_title']
    .str.lower()
    .str.strip()
)

# Identify software/tech engineer roles
tech_keywords = [
    'software', 'developer', 'engineer', 'programmer',
    'full stack', 'frontend', 'backend', 'data scientist',
    'machine learning', 'devops'
]

def is_software_engineer(title):
    if pd.isna(title):
        return False
    return any(keyword in title for keyword in tech_keywords)

us_df['is_software_engineer'] = us_df['job_title_clean'].apply(is_software_engineer)

# Filter to software engineers only
se_df = us_df[us_df['is_software_engineer']]

# Calculate the median total compensation
median_se_salary = se_df['total_comp'].median()

print(f"Median salary for Software Engineers in the U.S.: ${median_se_salary:,.0f}")
se_df[['job_title', 'state', 'total_comp']].head(10)


Median salary for Software Engineers in the U.S.: $126,000


job_title          state  total_comp
20              Data Programmer Analyst   Pennsylvania     74000.0
29                    Research Engineer          Texas     80000.0
40                        Lead Engineer        Georgia    150000.0
43          Principal Software Engineer   Pennsylvania    192500.0
46                     Mobile developer  Massachusetts    147100.0
50  Research and Development Engineer 3     California     96000.0
55             Water Resources Engineer  Massachusetts    106000.0
65                  Research Programmer   Rhode Island     70000.0
71                    Project engineer             NaN    125600.0
84                     Senior Engineer    Pennsylvania    118000.0

In [4]:
tech_industries = [
    'computing or tech', 'information technology', 'software', 'internet', 'web',
    'it services', 'computer services'
]

us_df['is_tech_worker'] = (
    us_df['industry'].str.lower().apply(
        lambda x: any(k in x for k in tech_industries) if isinstance(x, str) else False
    )
)

tech_df = us_df[us_df['is_tech_worker'] & us_df['state'].notna()]

# Average salary per state
state_avg_salary = (
    tech_df.groupby('state', dropna=True)['total_comp']
    .mean()
    .sort_values(ascending=False)
)

top_state = state_avg_salary.index[0]
top_state_salary = state_avg_salary.iloc[0]

print(f"🏆 Highest-paying US state for tech workers: {top_state} (${top_state_salary:,.0f} average total comp)")
state_avg_salary.head(10)

🏆 Highest-paying US state for tech workers: Georgia, Massachusetts ($474,000 average total comp)


state
Georgia, Massachusetts           474000.000000
Michigan, Texas, Washington      340000.000000
California, Oregon               250000.000000
California                       194085.562205
California, Colorado             193600.000000
Washington                       191271.688073
Colorado, Nevada                 190000.000000
New York                         181625.543027
Alabama, District of Columbia    166000.000000
Connecticut                      159041.666667
Name: total_comp, dtype: float64

In [5]:
import re
from scipy.stats import linregress

def midpoint_years(exp):
    if pd.isna(exp):
        return np.nan
    match = re.findall(r'\d+', exp)
    if len(match) == 1:
        return float(match[0])
    elif len(match) >= 2:
        return (float(match[0]) + float(match[1])) / 2
    return np.nan

tech_df['years_exp'] = tech_df['experience_overall'].apply(midpoint_years)

# Drop rows missing experience
exp_df = tech_df.dropna(subset=['years_exp', 'total_comp'])

# Fit linear regression: total_comp = a + b * years_exp
slope, intercept, r, p, se = linregress(exp_df['years_exp'], exp_df['total_comp'])

print(f"📈 Average salary increase per additional year of experience in tech: ${slope:,.0f}/year")
print(f"R-squared: {r**2:.3f}")


📈 Average salary increase per additional year of experience in tech: $1,847/year
R-squared: 0.024


/tmp/ipykernel_18577/1295380142.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tech_df['years_exp'] = tech_df['experience_overall'].apply(midpoint_years)


In [6]:
non_tech_df = us_df[~us_df['is_tech_worker'] & us_df['industry'].notna()]

industry_median = (
    non_tech_df.groupby('industry')['total_comp']
    .median()
    .sort_values(ascending=False)
)

top_industry = industry_median.index[0]
top_industry_salary = industry_median.iloc[0]

print(f"💼 Highest-paying non-tech industry: {top_industry} (median ${top_industry_salary:,.0f})")
industry_median.head(10)


💼 Highest-paying non-tech industry: Commercial Building Material Distribution (median $550,000)


industry
Commercial Building Material Distribution                         550000.0
Sports                                                            400000.0
Biotech / life sciences                                           346000.0
Biotech/pharmaceuticals                                           342000.0
pharma / medical device design and manufacturing                  288000.0
Energy (oil & gas & associated products, renewable power, etc)    285300.0
Pharmaceutical/biotechnology                                      284500.0
Petroleum                                                         284000.0
Corporate Training                                                280000.0
consulting                                                        265000.0
Name: total_comp, dtype: float64

In [8]:
summary = pd.DataFrame({
    'Question': [
        '1. Median salary for Software Engineers in the U.S.',
        '2. Highest-paying U.S. state for tech workers',
        '3. Avg. salary increase per year of experience in tech',
        '4. Highest-paying non-tech industry'
    ],
    'Answer': [
        f"${median_se_salary:,.0f}",
        f"{top_state} (${top_state_salary:,.0f})",
        f"${slope:,.0f} per year",
        f"{top_industry} (${top_industry_salary:,.0f})"
    ]
})

# Display neatly
summary.style.set_properties(**{
    'background-color': '#000000',
    'font-size': '14px',
    'border-color': '#ddd'
})


In [13]:
def classify_remote(row):
    # normalize strings
    city = str(row.get('What city do you work in?', '')).lower() if 'What city do you work in?' in row else ''
    state = str(row.get('state', '')).lower()
    
    # criteria for remote
    remote_keywords = ['remote', 'home', 'telecommute', 'wfh', 'hybrid', 'anywhere']
    if any(k in city for k in remote_keywords):
        return 'Remote'
    if state == '' or pd.isna(state):
        return 'Remote'
    return 'In-Office'

df['work_mode'] = df.apply(classify_remote, axis=1)

# Compute proportions (U.S. only to keep it consistent)
us_mode = df[df['country'] == 'united states']['work_mode'].value_counts(normalize=True) * 100

remote_pct = us_mode.get('Remote', 0)
office_pct = us_mode.get('In-Office', 0)

print(f"🏠 Remote workers: {remote_pct:.1f}%")
print(f"🏢 In-office workers: {office_pct:.1f}%")


🏠 Remote workers: 1.4%
🏢 In-office workers: 98.6%


## Step 3: Business Questions Analysis

Now answer those important business questions!


In [9]:
# Question 1: What is the median salary for Software Engineers in the United States?
print("$126,000")

$126,000


In [10]:
# Question 2: Which US state has the highest average salary for tech workers?
print("Georgia, Massachusetts ($474,000)")

Georgia, Massachusetts ($474,000)


In [11]:
# Question 3: How much does salary increase on average for each year of experience in tech?
print("$1,847 per year")

$1,847 per year


In [14]:
# Question 4: What percentage of respondents work remotely vs. in-office?
print("Remote workers: 1.4% vs In-office workers: 98.6%")

Remote workers: 1.4% vs In-office workers: 98.6%


In [12]:
# Question 5: Which industry (besides tech) has the highest median salary?
print("Commercial Building Material Distribution ($550,000)")

Commercial Building Material Distribution ($550,000)


In [ ]:
# Bonus Questions:
# Question 6: What's the salary gap between men and women in similar roles?
# Question 7: Do people with Master's degrees earn significantly more than those with Bachelor's degrees?
# Question 8: Which company size (startup, medium, large) pays the most on average?

## 🧾 Final Summary

**Summarize your findings here:**

1. **Median salary for Software Engineers in US:** **$126,000**  
2. **Highest paying US state for tech:** **Georgia / Massachusetts ($474,000)**  
3. **Salary increase per year of experience:** **$1,847 per year**  
4. **Remote vs office percentage:** **1.4% remote, 98.6% in-office**  
5. **Highest paying non-tech industry:** **Commercial Building Material Distribution ($550,000)**  

---

### **Key Insights**
- The **median Software Engineer salary** of $126K reflects strong mid-career compensation in the 2021 U.S. tech market.  
- **Georgia and Massachusetts** emerged as the top-paying states, possibly due to a few exceptionally high earners or localized tech clusters.  
- Salary increases about **$1.8K per year of experience**, indicating steady but modest wage growth tied to tenure.  
- The dataset shows **98.6% in-office** workers and only **1.4% remote**, consistent with the post-pandemic transition period in early 2021.  
- Outside of tech, **Commercial Building Material Distribution** offered the highest non-tech pay levels, likely reflecting senior leadership or niche technical roles.

---

### **Challenges Faced**
- **Unstructured and inconsistent data:**  
  Country and salary fields had inconsistent formatting (e.g., “US”, “U.S.A.”). Solved by cleaning text and mapping to standard formats.  
- **Extreme salary outliers:**  
  Salaries exceeding $1M distorted averages; filtered those using numeric bounds (`10,000 < total_comp < 1,000,000`).  
- **Ambiguous job titles:**  
  Required keyword-based categorization (e.g., “software”, “developer”, “engineer”) to isolate true tech professionals.

---

### **What I Learned About Vibe Coding**
- **Vibe coding = real-world problem-solving.** There’s no perfect step-by-step — just logical exploration guided by curiosity.  
- Learned to use **Python + pandas** for iterative data cleaning, validation, and statistical exploration.  
- Realized that the most valuable skill is the ability to **adapt**, spot inconsistencies, and make informed analytical judgments when data isn’t perfect.
